const infraConfig = {
  folders: [
    {
      id: "smart-classrooms",
      name: "Smart Classrooms",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "library",
      name: "Library",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "physics-lab",
      name: "Physics Lab",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "chemistry-lab",
      name: "Chemistry Lab",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "biology-lab",
      name: "Biology Lab",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "computer-lab",
      name: "Computer Lab",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "stem-lab",
      name: "STEM Lab",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "mini-auditorium",
      name: "Mini Auditorium",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "audio-visual-room",
      name: "Audio Visual Room",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "activity-room",
      name: "Activity Room",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "music-room",
      name: "Music Room",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "sick-room",
      name: "Sick Room",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "sports-room",
      name: "Sports Room",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
      ],
    },
    {
      id: "play-ground",
      name: "Play Ground",
      disc: "Air Force School, ASTE is located within Bangalore city limits. The school is one of the forerunners amongst the elite educational institutions in the city. It functions under the aegis of IAF educational and cultural society and is meant primarily for the children of Air Force personnel, Air Force School ASTE is recognised school up to XIIth class and affiliated with CBSE New Delhi. Air Force School, ASTE was started as a Nursery School in 1977 to cater to the educational needs of the children of Air Force personnel serving in HAL based units. Over the years, the school has grown in size up to XII std. Air Force School, ASTE functions from its two locations at Murgeshpalya Camp and Akash Vihar Camp and comprises of classes from Nursery to XII std.",
      images: [
        "/card3.png",
        "/card2.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
        "/card3.png",
        "/card2.png",
        "/card1.png",
        "/card1.png",
      ],
    },
  ],
};
export default infraConfig;
